# Sharding tutorial
# https://dzone.com/articles/composing-a-sharded-mongodb-on-docker

# mongo shell
# https://flaviocopes.com/mongodb/

# Shard: Each shard contains a subset of the sharded data. Each shard can be
# deployed as a replica set.

# Mongos (router): The mongos acts as query routers, providing an interface
# between client applications and the sharded cluster.

# Config servers: Config servers store metadata and configuration settings for
# the cluster.


#Mongod port defaults
#    27017 if mongod is not a shard member or a config server member
#    27018 if mongod is a shard member
#    27019 if mongod is a config server member

#
# [Router] [Router]
#      \    /
#       \  /
#        \/
#        |\
#        | \
#        |  \[Config servers, replica set]
#        |  / 
#        | / 
#        |/
#        /\  
#       /  \  
#      /    \  
# [Shard]   [Shard]



# db version v4.0.8

# Useful mongo shell commands within the docker instances
# db.isMaster() -> Returns useful information about an instance

################################################################################
# Define Shards: Each shard contains a subset of the sharded data. Each shard can
# be deployed as a replica set.

# Note the
# --replSet mongors1
# 'mongors1' Would indicate the replicaSet (maintains one common set of the data)

# We will build a replica set with these three nodes... 
# A replica set is a group of mongod instances that maintain the same data set.
################################################################################
version: '2'
services:
  replica1:
    image: mongo
    command: mongod --replSet myReplicaSet --dbpath /data/db --port 27017
    ports:
      # Host : Container
      - 27017:27017
    expose:
      - "27017"
    environment:
      TERM: xterm
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./replication/data1:/data/db
  replica2:
    image: mongo
    command: mongod --replSet myReplicaSet --dbpath /data/db --port 27017
    ports:
      - 27027:27017
    expose:
      - "27017"
    environment:
      TERM: xterm
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./replication/data2:/data/db

